### PR TITLE
chore: annotate errors

### LINKED ISSUE #3: Add support for annotations
We can use the `error` method from the `@actions/core` package to annotate the code directly in the pull requests and display the failures where they occurred. We can parse the file and line from the error stack.

Here's a Jest reporter that supports it: https://github.com/hipstersmoothie/jest-github-reporter

### PR DESCRIPTION
**Pull request by RomuloVitoi**
Annotation preview:

Screenshot 2023-03-15 at 17 59 38

Fixes #3

### CODE REVIEW

**Comment by RomuloVitoi** [comment]
We could use a library like https://www.npmjs.com/package/error-stack-parser or https://www.npmjs.com/package/stack-trace that parses the error stack and it would be more reliable.

The annotations that you're seeing in this PR is because we actually run the tests on the e2e compare and it creates the annotations.

**Comment by simoneb** [comment]
- Considering how popular those libraries are, I would go with one of them.
- On the annotations I'm still not sure, if we're running tests and they're failing, why is the build not failing?

**Comment by RomuloVitoi** [comment]
The build is not failing because the error is intentionally ignored by the `|| true` on https://github.com/nearform/node-test-github-reporter/blob/master/test/e2e/compare.sh#L13. The sample tests have errors that we're using to validate the report output.

**Comment by simoneb** [comment]
thanks for clarifying, lgtm

**Pull request merged**
